cadence:
  Accelerated VIP:
  - ACC_VIP_AMBA
  - ACC_VIP_AMBA_APB
  - ACC_VIP_AXI_3_4
  - ACC_VIP_AXI_3_4
  - ACC_VIP_AXI4_ACE
  - ACC_VIP_I2C
  - ACC_VIP_PCIE_5
  Allegro:
  - Allegro_performance
  - Allegro_studio
  - PCB_design_studio
  - SPECCTRA_HP
  - SPECCTRA_PCB
  - SPECCTRA_expert
  - Allegro_Viewer_Plus
  - Base_Verilog_Lib
  - Concept_HDL_studio
  - Extended_Verilog_Lib
  - expgen
  - pcomp
  - plotVersa
  COSLITE Access:
  - COSLITE_ACCESS
  CXL VirtualBridge Kit:
  - ACC_VIP_CXL
  - Vbridge_CXL_DA
  Cadence Quantus:
  - Advanced_sub_5nm_modeling
  - Advanced_sub_10nm_modeling
  - advanced_FF_modeling
  - advanced_modeling_20
  - QRC_Advanced_Analysis
  - DFM_Core_Technology
  - Virtuoso_QRC_Extraction_XL
  - Advanced_sub_5nm_modeling
  Cadence(R) SKILL Development Environment:
  - skillDev
  Celsius:
  - AdvancedPI
  - AdvancedPI_TI_20
  - SLNK
  - Celsius_CFD_Opt
  - SLNK
  - CelsiusDC
  - CelsiusDC_G
  - PowerDC
  - SLNK
  - Celsius_Thermal
  - Celsius_ThermalG
  - SLNK
  - Clarity_3DSolver
  - Clarity_3DSolverG
  - SLNK
  Clarity Advanced IC Package Extraction Suite:
  - Interposer_Extract_20
  - SLNK
  Conformal:
  - Conformal_Asic
  - Conformal_Custom
  - Conformal_Ultra
  - conformal_datapath
  - conformal_ldd
  - conformal_lec
  - conformal_lvr
  - conformal_mem
  - conformal_vhd
  - conformal_vlg
  - transformal_ltx
  - Conformal_ECO_GXL
  - Conformal_Low_Power_GXL
  Genus:
  - Genus_CPU_Opt
  - Genus_Low_Power_Opt
  - Genus_Physical_Opt
  - Genus_Synthesis
  Helium:
  - Helium_Base_Lib
  - Helium_Build_Batch
  - Helium_Build_GUI
  - Helium_SWD_GUI
  - Helium_Virtual_Runtime
  - Arm_FM00C
  - Helium_Gshift_RTLSWD_Opt
  - Helium_Lib_T1
  Indago Debug Analyzer App:
  - Affirma_sim_analysis_env
  - Indago_DA_App
  - Indago_DA_wAPI
  Innovus:
  - Innovus_5nm_Opt
  - Innovus_7nm_Opt
  - Innovus_CPU_Opt
  - Innovus_GigaPlace_XL_Opt
  - Innovus_GigaPlace_XL_Opt
  - Innovus_GigaPlace_GXL_Opt
  - Innovus_Hier_Opt
  - Innovus_hfr_Opt
  - Encounter_C
  - Innovus_C
  - Innovus_Impl_System
  - Innovus_MS_Opt
  - Innovus_PI_Opt
  JasperGold:
  - jasper_papp
  - jasper_pcov
  - jasper_pint
  - jasper_dao
  Joules RTL Power Solution:
  - Joules_RTL_Power
  Memory Model Portfolio:
  - MM_PORTFOLIO_CATALOG
  Memory Model for DDR5 (includes DDR4, DDR3 and DDR2) - Initi:
  - MM_ddr5sdram
  Memory Model for LPDDR5 (includes LPDDR4 and LPDDR3) - Initi:
  - MM_LPD5
  Modus DFT Option:
  - Modus_DFT_Opt
  Multi-Physics Universal HPC Accelerator:
  - MP_HPC_Token
  'Option: Palladium Series Memory-model Multiple Subscription':
  - ACCEL_MEM_VIP
  PCIe 5.0  VirtualBridge  Kit:
  - ACC_VIP_PCIE_5
  - Vbridge_PCIE_5_DA
  PDAPP Next Generation Product 100:
  - PDAPPENG100
  Variety:
  - Variety_LX_Client
  - Variety_LX_Server
  Palladium:
  - ACCEL_MEM_PLUS
  - ACCEL_MEM_VIP
  - Palladium_Z1_Compile
  - Palladium_Z1_Domain
  Protium:
  - Affirma_sim_analysis_env
  - Integrated_Metrics_Center
  - Palladium_XP_HDL_Checking
  - Protium2_Implementation_Debug
  - Protium4_Implementation_Debug
  - Protium_S1_Domain
  - Xcelium_Single_Core
  - Affirma_sim_analysis_env
  - Integrated_Metrics_Center
  - Palladium_XP_HDL_Checking
  - Protium2_Implementation_Debug
  - Protium_S1_Domain
  - Xcelium_Single_Core
  PureView:
  - VIP_PUREVIEW
  SiP Layout Bundle:
  - Allegro_PCB_Router_610
  - SiP_Layout_Bundle_1
  Sigrity:
  - AdvancedPI
  - AdvancedPI_20
  - SLNK
  - AdvPI_20_SystemPI_Opt
  - AdvancedSI
  - AdvancedSI_20
  - SLNK
  - PowerDC
  - SLNK
  - PowerSI
  - PowerSI_II
  - SLNK
  Spectre:
  - Spectre_char_opt
  - Affirma_sim_analysis_env
  - Spectre_AMS_MMSIM_Lk
  - Spectre_X_MMSIM_Lk
  - Virtuoso_APS_MMSIM_Lk
  - Virtuoso_Multi_mode_Simulation
  - Virtuoso_Spectre_GXL_MMSIM_Lk
  - Virtuoso_XPS_MMSIM_Lk
  VIP:
  - VIP_PORTFOLIO_CATALOG
  - VIP_UVC_3PSI_ENGINE
  - VIP_AHB_UVC
  - VIP_UVC_3PSI_ENGINE
  - VIP_AXI_ACE_5
  - VIP_AMBA5_CHIE
  - VIP_CCIX
  - VIP_CXL
  - VIP_CXL
  - VIP_USB_3_PS
  Virtual Debug Interface to Software Debuggers 4-pack:
  - ACC_VDEBUG
  VirtualBridge 8-Port Pack:
  - Vbridge_generic_port
  Virtuoso:
  - '111'
  - '940'
  - '945'
  - Virtuoso_Adv_Node_Framework
  - Virtuoso_Adv_Node_Opt_Layout
  - Virtuoso_Layout_Suite_EXL
  - Virtuoso_Layout_Suite_XL
  - Virtuoso_ADE_Assembler
  - Virtuoso_ADE_Verifier
  - Virtuoso_Schematic_Editor_XL
  Voltus:
  - DFM_Core_Technology
  - Voltus_Power_Integrity_XL
  - Voltus_Power_Integrity_AA
  Xcelium:
  - Affirma_sim_analysis_env
  - Integrated_Metrics_Center
  - Xcelium_Multi_Core
  - Affirma_sim_analysis_env
  - Integrated_Metrics_Center
  - Xcelium_Single_Core
  vManager Gen 4:
  - Vmanager_High_Availability
mentor:
  Calibre:
  - caldesignrev
  - calinteractive
  - calmultipattern
  - calmpadv
  - calibrepercadv
  - calibreperc
  - calibrepercsp
  - calpmatch
  - calibreqdb
  - verifdataport
  - calrealtime
  - calrealtimedig
  - calyieldenhance
  - calyieldserver
  - calibredrc
  - calibrehdrc
  - calibrelvs
  - calreconlvs
  - calibrehlvs
  - caldfmproperty
  - calibreadp
  - calibrexrc
  - calibrexrctoxact
  Catapult-Ultra Ap SW:
  - CatapultCPC_c
  - catapultlb_c
  - catapultlbfarm_c
  - CatapultUltra_c
  - CatapultVis_c
  - qdbg3p
  Questa Prime Ap SW:
  - msimcdebug
  - msimcompare
  - msimcoverage
  - msimdataflow
  - msimhdlmix
  - msimhdlsim
  - msimprofile
  - msimreguvm
  - msimsystemc
  - msimviewer
  - mtiverification
  - qdbgcoverage
  - qvman
  - qvrm
  - svverification
  - txanalysis
  - zncwmbase
  Tessent:
  - mttsacjtag_c
  - mttsbscan_c
  - mtcellmodgenpl_c
  - mtdiagnosis_c
  - mtcad_c
  - mtijtag_c
  - mttslogicbist_c
  - mttsmemorybist_c
  - mttsmembrepair_c
  - mttsminsystem_c
  - mtmissionmode_c
  - dftadvisor
  - mtscanpro_c
  - mtsi_c
  - mtssn_c
  - mttsmemorybist_c
  - mttestkompress_c
  - mtyieldinsight_c
  Veloce Hycon Ap SW:
  - hyconcheckpoint
  - plaidmm
  - s2stlmbridge
  - warpcore
  Veloce Softmodel Memory Library:
  - isolveahbmemsm
  - isolveaximemsm
  - isolvedbsm
  - isolveddr2sm
  - isolveddr3sm
  - isolveddr4sm
  - isolveddr5sm
  - isolveemmcsm
  - isolvegddr5sm
  - isolvegddr6sm
  - isolvehbmsm
  - isolvehmcsm
  - isolvei2csm
  - isolvelpddr2sm
  - isolvelpddr3sm
  - isolvelpddr4sm
  - isolvelpddr5sm
  - isolvelpddrsm
  - isolvenorflshsm
  - isolveonfism
  - isolvercdsm
  - isolvesdcardsm
  - isolveserflashsm
  - isolvestratasm
synopsys:
  DFT Compiler:
  - Test-CTL-Model
  - Test-Compiler
  - Test-Core-Wrapper
  - Test-DFTC-TMAX
  - Test-LBIST-Synthesis
  - Test-MBIST-Integration
  - Test-RTL-Check
  - Test-RTL-Tristate
  - Test-STDVR
  - Test-ScanRoute
  - Test-Validate
  DWC:
  - DWC-AMBA-AH5-Fabric-Source
  - DWC-AMBA-Fabric-Source
  - DWC-coreAssembler
  - DesignWare-AMBA-VIP
  - DesignWare-VERA
  - VIP-AMBA-AHB-SVT
  - VIP-AMBA-APB-SVT
  - VIP-AMBA-AXI-SVT
  - DWC-APB-Periph-Source
  - DesignWare-AMBA-VIP
  - DesignWare-VERA
  - VIP-AMBA-APB-SVT
  - DWC-AXI-DMAC
  - VIP-AMBA-AHB-SVT
  - VIP-AMBA-AXI-SVT
  - DWFC-Floating-Point
  - DWFC-div
  - DWFC-div-seq
  - DWFC-exp2
  - DWFC-ffp-add
  - DWFC-ffp-ffp2ffp
  - DWFC-ffp-mult
  - DWFC-ffp-norm
  - DWFC-fp-2sqrsum
  - DWFC-fp-3sqrsum
  - DWFC-fp-add
  - DWFC-fp-addcmp
  - DWFC-fp-addsub-dual
  - DWFC-fp-atan2-hps
  - DWFC-fp-avg2
  - DWFC-fp-avg4
  - DWFC-fp-cmp
  - DWFC-fp-div
  - DWFC-fp-div-seq
  - DWFC-fp-exp
  - DWFC-fp-ffp-add
  - DWFC-fp-ffp-mult
  - DWFC-fp-ffp2fp
  - DWFC-fp-fp2ffp
  - DWFC-fp-fp2fp
  - DWFC-fp-fp2fxp
  - DWFC-fp-fxp2fp
  - DWFC-fp-ln
  - DWFC-fp-macc
  - DWFC-fp-madd
  - DWFC-fp-mult
  - DWFC-fp-multifunc
  - DWFC-fp-scale
  - DWFC-fp-sqrt
  - DWFC-fxp-div
  - DWFC-ln
  - DWFC-lsd
  - DWFC-lzd
  - DWFC-multifunc
  - DWFC-norm
  - DWFC-pipe-mgr
  - DWFC-piped-fp-add
  - DWFC-piped-fp-madd
  - DWFC-piped-fp-mult
  - DWFC-piped-fp-multifunc
  - DWFC-sqrt
  Design Compiler NXT:
  - ACS
  - BOA-BRT
  - DC-Expert
  - DC-Extension
  - DC-SDF-Interface
  - DC-Ultra-Features
  - DC-Ultra-Opt
  - Design-Budgeting
  - Design-Compiler
  - Design-Compiler-NXT
  - Designware-Basic
  - Galaxy-Common
  - MCE-Base
  - Milkyway-Interface
  - RTLFusionVHDL
  - SynLib-Eval
  - VCS_UnifiedCompile
  Design Vision:
  - Design-Vision
  DesignWare Library:
  - DesignWare
  - DesignWare-LP
  - DesignWare-VERA
  - VIP-AMBA-AHB-SVT
  - VIP-AMBA-APB-SVT
  - VIP-AMBA-AXI-SVT
  - VT_CoverageURG
  Formality Base:
  - Formality
  - Formality-Advanced
  - Formality-E1
  - Formality-Ultra
  - Milkyway-Interface
  HAPS-80 Solution S104 -2:
  - HAPS-70-AMBA-XTOR-MASTER
  - HAPS-70-AMBA-XTOR-SLAVE
  - HAPS-80-AMBA-XTOR-MASTER
  - HAPS-80-AMBA-XTOR-SLAVE
  - HAPS-DX-AMBA-XTOR-MASTER
  - HAPS-DX-AMBA-XTOR-SLAVE
  - ProtoCompilerMP
  - ProtoCompilerS
  - ProtoCompilerS-RT
  - RtlGateCorrelation
  - RtlGateCorrelationSlave
  - VCSCompiler_Net
  - VHDL-Elaborator
  - VT_Assertions
  - VT_Coverage
  - VT_Testbench
  - VT_VCS_Xprop
  - mvdbgen
  - zs_Compil
  - zs_Emi3
  - zs_Emi3Runtime
  HDL Compiler Verilog:
  - HDL
  - HDL-Compiler
  - SynLib-Eval
  Library Compiler Base:
  - Library-Compiler
  NLP Add-On:
  - mvdbgen
  - mvsim
  Power Compiler:
  - Power-Optimization
  - RTL-Power-Analysis
  PrimePower Base:
  - PrimePower
  PrimeTime ADV:
  - GalaxyConstraint
  - Milkyway-Interface
  - PrimeTime
  - PrimeTime-ADV
  - PrimeTime-SI
  SpyGlass:
  - BasePolicySO
  - SG-Verdi-Plugin
  - VC-STATIC-COMPILE
  - checker
  - gui
  - mixed
  - oemunlock
  - save_restore
  - system_verilog
  - verilog
  - vhdl
  - adv_checker
  - lint_func
  - lint_soc_abstraction
  - turbo_struct
  - adv_checker
  - power_cge_regr
  - power_estso
  - power_high_perf
  - power_rednso
  VC Formal Ultra:
  - SNPS-ML-PLATFORM
  - VC-FORMAL-AEP-RT
  - VC-FORMAL-CC-RT
  - VC-FORMAL-FCA-RT
  - VC-FORMAL-FPV-RT
  - VC-FORMAL-FRV-RT
  - VC-FORMAL-FTA-RT
  - VC-FORMAL-FXP-RT
  - VC-FORMAL-RMA-RT
  - VC-FORMAL-RT
  - VC-FORMAL-SEQ-RT
  - VC-FORMAL-ULTRA
  - VC-ML-PLATFORM
  - VC-SMART-SEARCH
  - VC-STATIC-COMPILE
  - VCFV-Verdi-Plugin
  VC SpyGlass:
  - VC-CDC-BASE
  - adv_checker
  - cdc_adv_checker
  - VC-CONSTRAINTS-BASE
  - adv_checker
  - constraints_SDCgen
  - constraints_SDCmerge
  - constraints_mgmt
  - constraints_modemerge
  - constraints_soc_abstraction
  - constraintsso
  - txvso
  - VC-LINT-BASE
  - VC-STATIC-COMPILE
  - VC-STATIC-LINT
  - VC-STATIC-VERDI-PLUGIN
  - checker
  - BasePolicySO
  - SG-Verdi-Plugin
  - gui
  - mixed
  - oemunlock
  - save_restore
  - system_verilog
  - verilog
  - vhdl
  - VC-SG-RDC-Addon-Pkg
  - VC-RDC-BASE
  - adv_checker
  - rdc_adv_checker
  VC VIP:
  - VIP-AMBA-APB-SVT
  - VIP-AMBA-AXI-SVT
  - VIP-I2C-SVT
  - VIP-JTAG-SVT
  - VIP-LPDDR5-SVT
  - VIP-PCIE-G4-SVT
  - VIP-SOC-LIBRARY-SVT
  - VIP-SPI-BUS-SVT
  - VIP-SPI-SVT
  - VIP-UART-SVT
  VCS:
  - FusionVantageLmcInterface
  - Galil_Solver
  - LMCSwift_Net
  - SNPS-Assertions
  - VCSAMSCompiler_Net
  - VCSAMSRuntime_Net
  - VCSCompiler_Net
  - VCSMXCompiler_Net
  - VCSMXRunTime_Net
  - VCSPostProcDebugger_Net
  - VCSRuntime_Net
  - VCSTools_Net
  - VHDL-Analyzer
  - VHDL-Cycle-Sim
  - VHDL-Elaborator
  - VHDL-Event-Sim
  - VHDL-Tools
  - VHDL-VirSim
  - VT_Assertions
  - VT_AssertionsRuntime
  - VT_Coverage
  - VT_CoverageRuntime
  - VT_Testbench
  - VT_TestbenchRuntime
  - VT_VCS_AMS_CoSimRuntime
  - VT_Visual
  - XVCSDebugger
  - VCSCompiler_Net
  - VCSMXCompiler_Net
  - VCSMXRunTime_Net
  - VCSRuntime_Net
  - VCSTools_Net
  - VCSUltraCompiler_Net
  - VCSUltraRuntime_Net
  - VT_VCS_AMS_CoSimRuntime
  VDK Extension Add-on:
  - opengl_offload
  - pcie_realworld_io
  VDK Family for ARMv7v8 & DW:
  - VSDK.primary
  - VSDK.simulation
  - arm_cortex_base_library
  - arm_cortex_v7v8_base_library
  - arm_tlm_lib
  - synopsys_designware_tlm_lib
  - vdk_for_arm_cortex
  - vdk_for_arm_cortexv7v8
  VHDL Compiler:
  - HDL
  - SynLib-Eval
  - VHDL-Compiler
  Verdi:
  - VERDI-ULTRA
  - Verdi_HwSwDebug
  - Verdi
  - VerdiCoverage
  - VerdiSimDB
  - VerdiTransactionDebugUltra
  Virtualizer with ARMv7v8 & DW:
  - VAUTH.primary
  - VAUTH.simulation
  - arm_cortex_base_library
  - arm_cortex_v7v8_base_library
  - arm_tlm_lib
  - synopsys_designware_tlm_lib
